services:
  authentication-service-container:
    build:
      context: ./authentication-service
    ports:
      - "50001:50001"
    depends_on:
      - postgres-db-container

  users-service-container:
    build:
      context: ./users-service
    ports:
      - "50002:50002"
    depends_on:
      - postgres-db-container

  testing-management-service-container:
    build:
      context: ./testing-management-service
    ports:
      - "50003:50003"
    depends_on:
      - postgres-db-container

  api-gateway-container:
    build:
      context: ./api-gateway
    ports:
      - "50000:50000"
    depends_on:
      - authentication-service-container
      - users-service-container

  postgres-db-container:
    image: postgres:13
    environment:
      POSTGRES_DB: atms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "49999:5432"