spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
              - "http://147.45.146.190"
              - "http://195.133.145.69"
              - "https://195.133.145.69"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: login
          uri: http://authentication-service-container:50001
          predicates:
            - Path=/api/auth/login
          filters:
            - StripPrefix=1

        - id: users-service
          uri: http://users-service-container:50002
          predicates:
            - Path=/api/users/**, /api/roles/**, /api/permissions/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
              args:
                logMessage: Jwt validation filter executed in users-service

        - id: testing-management-service
          uri: http://testing-management-service-container:50003
          predicates:
            - Path=/api/projects/**, /api/test-cases/**, /api/test-plans/**, /api/steps/**, /api/task-management/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
              args:
                logMessage: Jwt validation filter executed in testing-management-service

        - id: public-api
          uri: http://testing-management-service-container:50003
          predicates:
            - Path=/public/**
          filters:
            - StripPrefix=1
            - name: PublicJwtValidation