spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1"
              - "http://147.45.146.190"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: login
          uri: http://localhost:50001
          predicates:
            - Path=/api/auth/login
          filters:
            - StripPrefix=1

        - id: users-service
          uri: http://localhost:50002
          predicates:
            - Path=/api/users/**, /api/roles/**, /api/permissions/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
              args:
                logMessage: Jwt validation filter executed in users-service

        - id: testing-management-service
          uri: http://localhost:50003
          predicates:
            - Path=/api/projects/**, /api/test-cases/**, /api/test-plans/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
              args:
                logMessage: Jwt validation filter executed in testing-management-service