spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: login
          uri: http://authentication-service-container:50001
          predicates:
            - Path=/api/auth/login
          filters:
            - StripPrefix=1

        - id: users-service
          uri: http://users-service-container:50002
          predicates:
            - Path=/api/users/**, /api/roles/**, /api/permissions/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
              args:
                logMessage: Jwt validation filter executed