spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: login
          uri: http://localhost:50001
          predicates:
            - Path=/api/auth/login
          filters:
            - StripPrefix=1

        - id: logout
          uri: http://localhost:50001
          predicates:
            - Path=/api/auth/logout
          filters:
            - StripPrefix=1

        - id: users-service
          uri: http://localhost:50002
          predicates:
            - Path=/api/users/**, /api/roles/**, /api/permissions/**
          filters:
            - StripPrefix=1
            - name: JwtValidation
              args:
                logMessage: Jwt validation filter executed